### ISSUE TITLE
module-json fails to build with gcc 5.4.0

### ISSUE THREAD

**Issue by pavelkveton** [qorelanguage/module-json#16]
make[2]: Entering directory '/home/kveton/src/qore/git/module-json/src'
/bin/bash ../libtool  --tag=CXX   --mode=compile g++ -std=c++11 -DHAVE_CONFIG_H -I. -I.. -I../include -I/home/kveton/omq/include  -I/home/kveton/src/qore/git/qore/include -D_GNU_SOURCE  -g -O2 -m64 -D_THREAD_SAFE  -O3 -Wall -MT single-compilation-unit.lo -MD -MP -MF .deps/single-compilation-unit.Tpo -c -o single-compilation-unit.lo single-compilation-unit.cpp
libtool: compile:  g++ -std=c++11 -DHAVE_CONFIG_H -I. -I.. -I../include -I/home/kveton/omq/include -I/home/kveton/src/qore/git/qore/include -D_GNU_SOURCE -g -O2 -m64 -D_THREAD_SAFE -O3 -Wall -MT single-compilation-unit.lo -MD -MP -MF .deps/single-compilation-unit.Tpo -c single-compilation-unit.cpp  -fPIC -DPIC -o .libs/single-compilation-unit.o
In file included from single-compilation-unit.cpp:2:0:
ql_json.cpp: In function ‘int do_json_value(QoreString_, QoreValue, int, ExceptionSink_)’:
ql_json.cpp:477:18: error: ‘isnan’ was not declared in this scope
       if (isnan(f) || isinf(f))
                  ^
ql_json.cpp:477:18: note: suggested alternative:
In file included from /usr/include/c++/5/random:38:0,
                 from /usr/include/c++/5/bits/stl_algo.h:66,
                 from /usr/include/c++/5/algorithm:62,
                 from /home/kveton/omq/include/qore/common.h:52,
                 from /home/kveton/omq/include/qore/Qore.h:45,
                 from qore-json-module.h:29,
                 from QC_JsonRpcClient.cpp:25,
                 from single-compilation-unit.cpp:1:
/usr/include/c++/5/cmath:641:5: note:   ‘std::isnan’
     isnan(_Tp __x)
     ^
In file included from single-compilation-unit.cpp:2:0:
ql_json.cpp:477:30: error: ‘isinf’ was not declared in this scope
       if (isnan(f) || isinf(f))
                              ^
ql_json.cpp:477:30: note: suggested alternative:
In file included from /usr/include/c++/5/random:38:0,
                 from /usr/include/c++/5/bits/stl_algo.h:66,
                 from /usr/include/c++/5/algorithm:62,
                 from /home/kveton/omq/include/qore/common.h:52,
                 from /home/kveton/omq/include/qore/Qore.h:45,
                 from qore-json-module.h:29,
                 from QC_JsonRpcClient.cpp:25,
                 from single-compilation-unit.cpp:1:
/usr/include/c++/5/cmath:621:5: note:   ‘std::isinf’
     isinf(_Tp __x)
     ^
Makefile:461: recipe for target 'single-compilation-unit.lo' failed

kveton@kvela:~/src/Qorus/git/qorus$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/5/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 5.4.0-6ubuntu1~16.04.1' --with-bugurl=file:///usr/share/doc/gcc-5/README.Bugs --enable-languages=c,ada,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-5 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-5-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-5-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-5-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.1)

**Comment by pavelkveton** [comment]
ok, it seems to be related to an issue #1005 - and really, json module used math.h

**Comment by pavelkveton** [comment]
the problem does not show up in 0.8.12, only in develop - probably it is related to c++11

**Comment by pavelkveton** [comment]
fixed, verified
